#!/bin/bash
# Created by Daniel Richards (ddrichar@ucsc.edu)
# on 11\14\17 

if [ $1 == '-h' ]; then
   printf "findTargets --help \n   findTargets is a simple script that cleans, makes(a .jar file) and runs SetiTargets\n"
   printf "   If your targets are in targets.txt and your config.txt is correctly configured, all\n" 
   printf "   you need to do is run ./findTargets.\n\n"
   printf "Optionally, you can provide findTargets with an output with ./findTargets <output.txt>\n\n"
   printf "Created by Daniel Richards github.com/danieldrichards \n\n"
 	exit

fi
if ! make -q; then
	echo "------- Cleaning -------"
	make clean 
	echo "-------- Making --------"
	make 
fi
	echo "-------- Running --------"

if [ $# == 1 ]; then
	java -jar ./SetiTargets.jar > $1
	printf "\n\n--------------------  Resut File ---------------------\n"
	cat $1
else
	java -jar ./SetiTargets.jar
fi






